### Numpy to Tensor

In [1]:
import numpy as np
import torch

In [2]:
# np.ndarray and torch.tensor
n_array = np.arange(10).reshape(2,5)
t_array = torch.FloatTensor(n_array)

print(n_array)
print(t_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])


In [3]:
# can use slicing and indexing
print(n_array[:, 2:])
print(t_array[:, 2:])

[[2 3 4]
 [7 8 9]]
tensor([[2., 3., 4.],
        [7., 8., 9.]])


In [4]:
# same methods 
print(n_array.ndim)
print(t_array.ndim)

2
2


In [5]:
# np.ndarray.shape == torch.tensor.size()
print(n_array.shape)
print(t_array.size())

(2, 5)
torch.Size([2, 5])


In [6]:
# np.ndarray.reshape() = torch.tensor.view()
print(n_array.reshape(5,2))
print(t_array.view(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [7]:
n1 = np.arange(16).reshape(2,8)
n2 = np.arange(16).reshape(8,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

In [8]:
# np.ndarray.dot() == torch.tensor.matmul()
print(n1.dot(n2))
print(t1.matmul(t2))

[[280 308]
 [728 820]]
tensor([[280., 308.],
        [728., 820.]])


In [9]:
# np.ndarray.methods(axis=n) == torch.tensor.methods(dim=n)
print(t1.mean())
print(t1.mean(dim=0))
print(t1.mean(dim=1))

tensor(7.5000)
tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
tensor([ 3.5000, 11.5000])


In [10]:
n1 = n1.reshape(4, 4)
n2 = n2.reshape(4, 4)
t1 = t1.view(4, 4)
t2 = t2.view(4, 4)

In [11]:
# torch.tensor's wise element operation
print(n1 * n2)
print(t1 * t2)
print(t1.mul(t2))
print(t1 * 3)
print(t1.mul(3))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.]])
tensor([[ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.],
        [24., 27., 30., 33.],
        [36., 39., 42., 45.]])
tensor([[ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.],
        [24., 27., 30., 33.],
        [36., 39., 42., 45.]])


In [12]:
# handling dim method in torch.tensor
print(t1.view(-1, 16).size())
print(t1.view(-1, 16).squeeze().size())
print(t1.view(-1, 16).unsqueeze(dim=2).size())

torch.Size([1, 16])
torch.Size([16])
torch.Size([1, 16, 1])


### Tensor Operations for DL Formula

In [13]:
import torch
import torch.nn.functional as F

In [14]:
# torch.nn.functional has many functions
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [15]:
tensor = torch.randint(5, (10, 5))
tensor

tensor([[0, 2, 3, 4, 1],
        [1, 1, 3, 1, 0],
        [1, 1, 1, 1, 2],
        [3, 0, 4, 2, 2],
        [1, 4, 3, 3, 2],
        [1, 4, 2, 4, 2],
        [4, 1, 4, 3, 4],
        [3, 3, 4, 4, 2],
        [2, 4, 1, 2, 1],
        [4, 3, 2, 0, 3]])

In [16]:
tensor = tensor.argmax(dim=1)
tensor

tensor([3, 2, 4, 2, 1, 1, 0, 2, 1, 0])

In [17]:
tensor = F.one_hot(tensor)
tensor

tensor([[0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])

### Torch AutoGrad

$$
y = w^2 \\
z = 2y + 5 \\
\frac{\partial{z}}{\partial{w}}=4w \\
$$

In [18]:
# torch.tensor has attribute associated grad
w =  torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y + 5

In [19]:
print(type(y))
print(type(z))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [20]:
# torch.tensor has backward() and grad
z.backward()
print(w.grad)

tensor(8.)


$$
Q = 3a^3 - b^2 \\
\frac{\partial{Q}}{\partial{a}}=9a^2 \\
\frac{\partial{Q}}{\partial{b}}=-2b \\
$$

In [21]:
# required_grad parameter is default True
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2

In [22]:
external_grad = torch.tensor([1., 1.])
Q.backward(external_grad)

print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])


### AutoGrad for Linear Regression

In [23]:
import numpy as np
import torch
import torch.nn.functional as F
from torch.autograd import Variable

$$
y = 2x + 1
$$

In [24]:
# create the samples
x_train = np.arange(11).reshape(-1, 1)
y_train = 2 * x_train + 1 + np.random.uniform(-0.5, 0.5)

In [25]:
# define model
class MyLinearRegression(torch.nn.Module) :
    def __init__(self, input_size, output_size) :
        super(MyLinearRegression, self).__init__()
        self.linear = torch.nn.Linear(input_size, output_size)
    
    def forward(self, x) :
        out = self.linear(x)
        return out

In [26]:
# hyper parameter setting
input_dim = 1
output_dim = 1
lr = 0.01
epochs = 100

# create model
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
model = MyLinearRegression(input_dim, output_dim)
loss = torch.nn.MSELoss()
optm = torch.optim.SGD(model.parameters(), lr=lr)

# set device for using
model.to(device)
input_data = Variable(torch.FloatTensor(x_train).to(device))
label_data = Variable(torch.FloatTensor(y_train).to(device))

In [27]:
# model training
for epoch in range(epochs) :
    # reset optimizor 
    optm.zero_grad()
    # forward propagation
    y_pred = model.forward(input_data)
    # calculate loss
    loss_out = loss(y_pred, label_data)
    # back propagation
    loss_out.backward()
    # update parameters
    optm.step()
    if epoch % 10 == 0 or epoch == 99 :
        print(f'epoch:[{epoch}], loss:[{loss_out:.5}]')

epoch:[0], loss:[39.828]
epoch:[10], loss:[0.0099122]
epoch:[20], loss:[0.0088593]
epoch:[30], loss:[0.0079183]
epoch:[40], loss:[0.0070772]
epoch:[50], loss:[0.0063255]
epoch:[60], loss:[0.0056536]
epoch:[70], loss:[0.0050531]
epoch:[80], loss:[0.0045163]
epoch:[90], loss:[0.0040366]
epoch:[99], loss:[0.0036486]


In [28]:
# predict value
model.forward(input_data)

tensor([[ 0.8451],
        [ 2.8613],
        [ 4.8775],
        [ 6.8936],
        [ 8.9098],
        [10.9260],
        [12.9422],
        [14.9584],
        [16.9746],
        [18.9907],
        [21.0069]], device='cuda:0', grad_fn=<AddmmBackward>)

In [29]:
# model's parameters
list(model.parameters())

[Parameter containing:
 tensor([[2.0162]], device='cuda:0', requires_grad=True), Parameter containing:
 tensor([0.8451], device='cuda:0', requires_grad=True)]